[servers]
192.168.5.14 ansible_user=areg ansible_ssh_pass=adminareg ansible_become_pass=adminareg nginx_site="xsoft.local"

[clients]
192.168.5.16 ansible_user=client1areg ansible_ssh_pass=adminpass  ansible_become_pass=adminpass nginx_site="xsoft.local"
192.168.5.15 ansible_user=client2areg ansible_ssh_pass=adminpass  ansible_become_pass=adminpass nginx_site="xsoft.local"

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
